### ISSUE TITLE
FIX: Text is not coming at homepage of this app.

### ISSUE THREAD

**Issue by Saksham2k3s** [Saksham2k3s/LinksFinder#1]
Some text is not coming at the home page of this app.

At localhost:3000 it is coming like that 
![withtext](https://github.com/Saksham2k3s/LinksFinder/assets/129402285/057b5cd3-2d7f-4440-9af9-4f9013fb9c61)

But when I open it on my deploy site (https://saksham2k3s.github.io/LinksFinder/) it is not coming  
![withouttext](https://github.com/Saksham2k3s/LinksFinder/assets/129402285/68e856fe-8373-4fb9-8f8a-244bcce63bd3)

**Comment by bilalshaikh292** [comment]
heyy is the issue still open ? I would like to contribute ?

**Comment by Saksham2k3s** [comment]
Hey @bilalshaikh292 ,
Yes, this issue is now open. If you can, please go ahead and resolve it."
