### ISSUE TITLE
FEAT : Card Height Changes Dynamically with Description Length

### ISSUE THREAD

**Issue by Saksham2k3s** [Saksham2k3s/LinksFinder#11]
First click to star button.

### Description:

When adding a description to the card in `CourseCard.jsx`, the card height dynamically changes. To address this, let's implement a solution where a fixed number of letters is shown in the card description, with a "Read More" option. Clicking on "Read More" should open a modal displaying the full description.

### Steps to Reproduce:

- Add a description with varying lengths to the cards.
- Observe the dynamic change in card height.

### Expected Behavior:

The card height should remain fixed, and a truncated version of the description should be displayed with a "Read More" option. Clicking on "Read More" should open a modal with the full description.

### Proposed Solution:

Modify `CourseCard.jsx`  to implement a fixed-length description with a "Read More" option that opens a modal.

**Comment by shadow-ryu** [comment]
Hey can I work on this?

**Comment by shadow-ryu** [comment]
"I'm seeking your opinion on whether I should utilize Material-UI for modals or create a custom modal. I'm a bit uncertain, especially considering that you have Material-UI available but don't necessarily use it yourself."

**Comment by shadow-ryu** [comment]
I'm seeking your opinion on whether I should utilize Material-UI for modals or create a custom modal. I'm a bit uncertain, especially considering that you have Material-UI available but don't necessarily use it yourself.

**Comment by Saksham2k3s** [comment]
> I'm seeking your opinion on whether I should utilize Material-UI for modals or create a custom modal. I'm a bit uncertain, especially considering that you have Material-UI available but don't necessarily use it yourself.

@shadow-ryu  Use custom modal
