### ISSUE TITLE
FIX: Make the navbar responsive as it was not displaying properly on certain mobile screens.

### ISSUE THREAD

**Issue by Saksham2k3s** [Saksham2k3s/LinksFinder#7]
### Description
Make the navbar responsive as it's not displaying properly on certain mobile screens.
![notrespo](https://github.com/Saksham2k3s/LinksFinder/assets/129402285/28940f88-6e41-45e8-800c-fd34a9fea693)

**Comment by IrfanSalim** [comment]
Hey, I would like to take this up

**Comment by Afeayo** [comment]
Hi, I will like to work on this
